
spring:
  profiles:
      active: dev
  datasource:
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20

mybatis:
   mapper-locations: classpath:mapper/*.xml
   type-aliases-package: com.straw.slave.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
---
spring:
    application:
        name: cruncher
    profiles: dev
    datasource:
        url: jdbc:mysql://localhost:3306/idiom
        username: root
        password: 1234
        driverClassName: com.mysql.jdbc.Driver
server:
    port: 9000


---
spring:
    application:
        name: cruncher
    profiles: prod
    datasource:
        url: jdbc:mysql://104.128.82.190:3306/idiom
        username: root
        password: 123456
        driverClassName: com.mysql.jdbc.Driver
server:
    port: 9000


